apiVersion: v1
kind: Service
metadata:
  name: outboxpayment
  labels:
    app: outboxpayment
spec:
  clusterIP: None
  selector:
    app: outboxpayment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outboxpayment
  labels:
    app: outboxpayment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outboxpayment
  template:
    metadata:
      labels:
        app: outboxpayment
    spec:
      containers:
      - name: outboxpayment
        image: outboxpayment
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/payments
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: verysecret
